### ISSUE TITLE
error occurred

### ISSUE THREAD

**Issue by ForrestPi** [SonSang/dmesh#9]
when run bash run_all.sh
error occurred

Traceback (most recent call last):
  File "/home/code/dmesh/exp/1_mesh_to_dmesh.py", line 16, in <module>
    from diffdt import DiffDT
  File "/home/code/dmesh/diffdt/__init__.py", line 5, in <module>
    from diffdt.pd import PDVertexComputationLayer, PDStruct
  File "/home/code/dmesh/diffdt/pd.py", line 8, in <module>
    from . import _C
ImportError: /home/code/dmesh/diffdt/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3tbb6detail2r117deallocate_memoryEPv

**Comment by SonSang** [comment]
Hi, sorry for the late reply. I hope you fixed this installation error.
If you couldn't, can you please verify if there was no error when you ran `pip install -e .` on the root folder?
It seems that the source codes in `diffdt` folder were not compiled correctly.
